function TileType() {
}

TileType.GAP = 0;
TileType.FULL_FLOOR_GRASS_TOP = 1;
TileType.FULL_FLOOR_GRASS_TOP_FRONT_EDGE = 3;
TileType.FULL_FLOOR_GRASS_TOP_BACK_EDGE = 4;
TileType.FULL_FLOOR_DIRT = 2;
TileType.FULL_FLOOR_DIRT_FRONT_EDGE = 5;
TileType.FULL_FLOOR_DIRT_BACK_EDGE = 6;

